language: julia

os:
  - osx
  - linux
  - windows
  - freebsd

julia:
  - 1
  - nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

jobs:
  allow_failures:
    - julia: nightly
